Implement handling of Geometry type
borisdj/EFCore.BulkExtensions pull request #420
Opened 2020-10-26 16:09 UTC by Farami

This allows bulk inserting and updating of NetTopologySuites Geometry type.
By default it will use SRID 4326, which is the default SRID for MSSQL.

2020-10-26 16:10 UTC, Farami commented
This will resolve #88.

2020-11-01 13:25 UTC, tejsj commented
+1

This feature would be so nice!

2020-12-09 11:10 UTC, valdas1 requested changes
Changes to EFCore.BulkExtensions/SqlBulkOperation.cs

I have a question about setting the IsGeography property of SqlServerBytesWriter to true, and the handling of the differences between geometry and geography types.

I'm not quite sure the current version would work, so if anyone could do a quick review, or write a comment, that would be great.

2020-12-09 11:10 UTC, valdas1 commented on EFCore.BulkExtensions/SqlBulkOperation.cs
> +                    {
Add a check for propertyType equals geometry, and change sqlServerBytesWriter (line 718) IsGeography property to false.
```
if propertyType == typeof(Geometry)
{
    sqlServerBytesWriter.IsGeography = false;
}
```

2020-12-12 23:57 UTC, borisdj commented
I have merged some previous PullRequest, so could you first resolve current conflicts.
Thx for contrib.

2021-02-25 09:54 UTC, miloszskalecki commented
Hi Guys, any news on this fix?

2021-03-08 12:48 UTC, borisdj commented
I have managed to manually integrate the proposed solution to the latest version.

2021-03-08 12:48 UTC, closed without merging